<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <Compile Include="../Shared/*.cs" LinkBase="Shared" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.Fusion.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>

  <ItemGroup>
    <None Update="gateway.far" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
